spring:
  datasource:
    url: jdbc:mysql://proxysql:6033/community?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:appuser}
    password: ${DB_PASSWORD:apppass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false  # 운영환경에서는 false 권장
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false  # 운영환경에서는 false 권장

logging:
  level:
    org.hibernate.SQL: WARN  # 운영환경에서는 WARN 또는 ERROR 권장

server:
  port: 7777
