name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      # 0. 실행 권한 부여 (Gradle Wrapper)
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      # 1. 소스코드 체크아웃
      - name: Checkout source
        uses: actions/checkout@v3

      # 2. JDK 설치
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Gradle 캐시 설정 (Gradle 프로젝트일 경우)
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # 4. Gradle 빌드 실행
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 5. Docker Buildx 설치
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 6. DockerHub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: developmentgoldman/communityboard-app:latest

      # 8. 빌드 실행 권한 부여
      - name: Make build script executable
        run: chmod +x ./build.sh

