name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스코드 체크아웃
      - name: Checkout source
        uses: actions/checkout@v3

      # 2. JDK 설치
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Gradle 캐시 설정
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # Gradle Wrapper 실행 권한 부여
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      # 4. Gradle 빌드 실행 (테스트 제외)
      - name: Build with Gradle
        run: ./gradlew clean build -x test
        # 실행 권한 부여
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      # 5. 프론트엔드 npm 설치
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          npm install
          chmod +x ./node_modules/.bin/vue-cli-service

      # 6. 프론트엔드 빌드
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # 7. Docker Buildx 설치
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 8. DockerHub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 9. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: developmentgoldman/communityboard-app:latest

      # 10. 빌드 스크립트 실행 권한 부여 (선택)
      - name: Make build script executable
        run: chmod +x ./build.sh
